language: node_js
node_js: 9
branches:
  only:
  - dev
  - master
deploy:
  provider: heroku
  app:
    dev: dev-shipcollision
    master: shipcollision
  skip_cleanup: true
  api_key:
    dev:
      secure: K3OHpiG9yt+ZqwaAxW6Xj/3HHJllcIHjeVdiQQ1DeBY8WADSmHaT/AToAwUxLKMBED3bx6BAvXH0gsvA7DlgfYBdl73vIvmjHd6n+tX9qHvNCF6hlLvEiVsn/0HSaM/eZm5APvCrLIySE3GTzVAWAuBYWBdRfPE51PRQ6cpRNxmn3FX4lkqK00J8yJV+85T00Aw1EPMD2v8g1mjSrngeeiOPSynvDAO44VFqmp0oILmOyo7V13ZdBC2jxw1anmPAf6Hul8jOM+bW6YaeeA4k1e9HE9eP54MAkUT6N3mndLWiFHZboX/4XQp3tD0UteSvKkgR6AEZ2rpOuJO4HJ2f9hqLvZYdhUgfAzDgGwC1inxFoLCU9LzcY2YDTvzdjLJaJEb+i9YXoZ+sJ6NhqXXC2H8FM6ufzsaKSQfpDxVE7VUU57N5KIsZ0PJ6+kuB36vwQmQsbMDuOUWmji5k2hF6NPtrrJxH/xKiTILzB7JfACxPY81/Re0AXSUEbXyt/MVxp7h7F/lum+GkHHcCzWDDsXrG8uz6m9eIV25GamLiSOk1CXPNgnObcP+6AI8jthng/ohJ1HkMVNc23pMoUPz4tQCEYwPHOlSPlGHft6mkTMGFRBFZbf0h8N4xJu96x5htFIMF7uHFh4WEMnN59tHjckOCcDm0otyPQk94ZFL9JAA=
    master:
      secure: MR441Bo50zD3UvHxCvaVkiDYHWpMWFkau47ADHIrlhKiPp3Ij/YQKOAlhRpIuidgnw8wuTqAt4ZnnIX3DjRsWVVj1XLfGzyc+/WtTP4t7yEldYWAsz9msj2uzvPMFOJiIvLA3VHCGVFP92KzwXrFRJ6Ga2QARMYuru73XL08rD0xWTDzAO+Zj8VvLK2nw7cqXi78ABVbXr4BAG42fzvcw9dvyB39um9LbQu8sW+1Be4aUvaccK8jFd8mws6AVCmJQ8VibWRdekXPj1XhXyUGJCLAKafS59X6BFehBlFbYfEkTJlSy/q77uVXRSXbunW2sHDCdLTB5+Req9bWHvGl5SgJpPRFGzYc1wSAu/4gZ7R1o0fv3bZBHjLeUrTu4e/W00GS2Mr3loY56at8nrmOAy5XHO2EXXx3D9rWZBtz5wJywLK7rCeoLA1elaw89bgwR/yCZdD+Lml3GODtO7HjjFu32c4wk5JwUEgJDEQhc2osrTTsf8jVAkXaN2Ma1dhsw2reck0hp9B0LGylL+BPBn6Iv3SK8g3qbyG3T0/S8cB75ArCPJM2s3uiuhv3SZCWjil/xWlW45XmFcgFusAwLj5xzmlT20xGCTBV0UY0HZP7L76o4WA+HVSunZIifZw7IMUON3mg2e3Lpq+9CT+0bUyl1pKRlQqMCFd4jFzqFbk=
